### ISSUE TITLE
Move repo to Github

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rquinio/l10n-maven-plugin#13]
```
googlecode is a bit lacky in terms of features/usability, and it may hinder 
others to contribute. I was thinking of moving the repo to Github.
```

Original issue reported on code.google.com by `romain.q...@gmail.com` on 11 Jul 2014 at 7:38

**Comment by seanf** [comment]
The code and issues seem to have been moved to github, but it looks as if the wiki hasn't been migrated (yet?).  For instance, pages like https://code.google.com/p/l10n-maven-plugin/wiki/Usage

**Comment by rquinio** [comment]
Yeah, the automatic import has put the wiki pages on a "wiki" branch, for instance: https://github.com/rquinio/l10n-maven-plugin/blob/wiki/Usage.md ...

I think separate branch is not good, it should either be in master branch with links from the README, or using github wiki feature.

**Comment by seanf** [comment]
The github wiki, when enabled, is set up as its own git repo, so you might just be able to push the existing `wiki` branch to `git@github.com:rquinio/l10n-maven-plugin.wiki.git`.

https://help.github.com/articles/adding-and-editing-wiki-pages-locally/

**Comment by rquinio** [comment]
Thanks, everything should be moved to github wiki now, with proper internal links !
There's a remaining problem of horizontal scrolling on tables due to github narrow layout...
I'll check how other maven plugins handle this.

**Comment by rquinio** [comment]
Documentation has now been updated to fit github format.
