### ISSUE TITLE
Multi-module reports

### ISSUE THREAD

**Issue by jason-p-pickering** [rquinio/l10n-maven-plugin#16]
Hi there. I came across this tool today, and looks like it is exactly what we need. Thanks a lot. 

I have gone through the examples and am trying to setup a multi-module report, but am failing. 

I tried the example from the source code (l10n-maven-plugin/src/it/report-multi-module) which runs fine. When generating the report from the main pom however, the individual modules sites are not linked correctly. Specifcally, these files are missing l10n-maven-plugin-report-multi-moduleA-it/index.html

What am I missing?

Thanks again for the great tool!

Regards,
Jason

**Comment by rquinio** [comment]
Hi, glad you find the plugin useful !
It seems index.html is not generated by default, and needs to be explicitly added via maven-project-info-reports-plugin (cf https://issues.apache.org/jira/browse/MSITE-425)
I've fixed it on report-multi-module IT.

**Comment by jason-p-pickering** [comment]
Hi Romain,
Thanks again for your quick response and fix. This is not working for me, so I am closing the issue. 

Regards,
Jason
