### ISSUE TITLE
Recursive search of bundles in mentioned folders

### ISSUE THREAD

**Issue by Efremenkov** [rquinio/l10n-maven-plugin#17]
In many projects structure of packages for resource files is the same as for the packages of source files.
It would be good if recursive search of resource files was possible in the folders containing in mentioned directories.
It refers to propertyDir tag.

**Comment by rquinio** [comment]
Indeed that makes sense, and it will combine nicely with #15 for inclusions/exclusions.

**Comment by rquinio** [comment]
Something missing for proper reporting is to use fully qualified names for bundles (recursive path), as there could be two bundles with the same name in different folders.
