### ISSUE TITLE
Not only ".properties"

### ISSUE THREAD

**Issue by Efremenkov** [rquinio/l10n-maven-plugin#18]
It would be fine if plugin could process not only ".properties" files.

**Comment by rquinio** [comment]
This should come with #15. However I'm curious if they are any other "standard" file extensions that maybe should be included by default ? Do you have examples ?

**Comment by Efremenkov** [comment]
Sorry for long response. 
I mean the extension name but not the structure of resource files. For example the extension is ".messages" but the structure of the file is the same as in".properties" - key:value.

**Comment by Efremenkov** [comment]
Sorry for long response.
Actually I mixed up things, you are right ".properties" files is standart for bundles. 
Sorry, it isn't necessary.
